## Config Server
#spring:
#  config:
#    import: optional:configserver:http://localhost:8888 # bootstrap 사용 안하고 설정
#  cloud:
#    config: # 기본 gateway-service.yaml 사용
#      # name: common
#      profile: dev # gateway-service-dev.yaml 사용

spring:
  config:
    import: optional:configserver:http://localhost:8888 # bootstrap 사용 안하고 설정
  cloud:
    config:
      name: config-server